
import Layout from '@/components/Layout';
import { FileText, Scale, AlertTriangle, CheckCircle, Users, Globe } from 'lucide-react';

const Terms = () => {
  const sections = [
    {
      icon: Users,
      title: 'Acceptance of Terms',
      content: 'By using SmartName AI, you accept and agree to be bound by these terms of service. If you do not agree with any part of these terms, please discontinue use of our service immediately.'
    },
    {
      icon: CheckCircle,
      title: 'Service License',
      content: 'We grant you a limited, non-exclusive license to use SmartName AI for personal and commercial name generation. This license may be revoked if you violate these terms or misuse our service.'
    },
    {
      icon: AlertTriangle,
      title: 'Acceptable Use',
      content: 'You agree to use SmartName AI responsibly and not for any illegal, harmful, or inappropriate purposes. We reserve the right to suspend accounts that violate our community standards.'
    },
    {
      icon: Globe,
      title: 'Generated Content',
      content: 'Names generated by SmartName AI are suggestions only. You are responsible for conducting trademark searches and ensuring legal availability before using any suggested names commercially.'
    }
  ];

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-12">
          <Scale className="w-16 h-16 text-brand-primary mx-auto mb-4" />
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            <span className="gradient-text">Terms of Service</span>
          </h1>
          <p className="text-xl text-white/70 max-w-3xl mx-auto leading-relaxed">
            Please read these terms carefully before using SmartName AI services.
          </p>
        </div>

        {/* Last Updated */}
        <div className="card-glass p-4 mb-8 text-center">
          <p className="text-white/60">
            <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Introduction */}
        <div className="card-gradient p-8 mb-8">
          <h2 className="text-2xl font-bold text-white mb-4 flex items-center space-x-2">
            <FileText className="w-6 h-6 text-brand-primary" />
            <span>Service Agreement</span>
          </h2>
          <p className="text-white/80 leading-relaxed mb-4">
            These Terms of Service govern your use of SmartName AI business name generation 
            service. By accessing or using our service, you agree to comply with these terms.
          </p>
          <p className="text-white/70 leading-relaxed">
            We may update these terms periodically. Continued use of our service after 
            changes constitutes acceptance of the updated terms.
          </p>
        </div>

        {/* Terms Sections */}
        <div className="space-y-6 mb-8">
          {sections.map((section, index) => (
            <div key={index} className="card-glass p-6">
              <div className="flex items-center space-x-3 mb-4">
                <section.icon className="w-6 h-6 text-brand-primary" />
                <h2 className="text-xl font-bold text-white">{section.title}</h2>
              </div>
              <p className="text-white/70 leading-relaxed">{section.content}</p>
            </div>
          ))}
        </div>

        {/* Service Quality */}
        <div className="card-gradient p-8 mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">Service Quality</h2>
          <div className="space-y-4 text-white/80">
            <p className="leading-relaxed">
              We strive to provide high-quality name suggestions and maintain reliable service 
              availability. However, we cannot guarantee that all generated names will be 
              legally available or suitable for your specific needs.
            </p>
            <p className="leading-relaxed">
              We reserve the right to modify, suspend, or discontinue any aspect of our 
              service with reasonable notice when possible.
            </p>
          </div>
        </div>

        {/* Important Notice */}
        <div className="card-glass p-6 mb-8">
          <h2 className="text-xl font-bold text-white mb-4 flex items-center space-x-2">
            <AlertTriangle className="w-5 h-5 text-yellow-400" />
            <span>Important Legal Notice</span>
          </h2>
          <div className="bg-yellow-400/10 border border-yellow-400/20 rounded-lg p-4">
            <p className="text-white/80 leading-relaxed">
              <strong>Trademark Disclaimer:</strong> SmartName AI generates name suggestions 
              based on your input but does not conduct trademark searches. You are solely 
              responsible for verifying the legal availability of any names before commercial use.
            </p>
          </div>
        </div>

        {/* Contact */}
        <div className="card-gradient p-8 text-center">
          <h2 className="text-2xl font-bold text-white mb-4">Questions About These Terms?</h2>
          <p className="text-white/80 leading-relaxed mb-6">
            If you have questions about these Terms of Service, please contact our support team.
          </p>
          <div className="space-y-2 text-white/70">
            <p><strong>Email:</strong> support@smartnameai.app</p>
            <p><strong>Response Time:</strong> Within 24-48 hours</p>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Terms;
